### ISSUE TITLE
Hyper changed format of themes

### ISSUE THREAD

**Issue by MateuszKubuszok** [markelog/hyperterm-twilight#2]
With current version of Hyper.js and twillight theme installed none of the colors is properly set.

After checking out [this comment](https://github.com/zeit/hyper/issues/294#issuecomment-357375621) I can confirm, that manually changing a list to an object (`colors`) make them work again.

**Comment by markelog** [comment]
Rrrr. It's a bit upsetting that they broke themes like that.

Anyways, It seems you did all the work then :). Would you like to send a PR for it?

**Comment by MateuszKubuszok** [comment]
Sure :) Please review: https://github.com/markelog/hyperterm-twilight/pull/3
